Fail if tests failed

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -75,3 +75,10 @@ jobs:
 
       - name: Stop containers
         run: docker compose -f docker-compose.test.yml down
+
+      - name: Fail if tests failed
+        run: |
+          if [[ "${{ env.failed }}" -ne 0 ]]; then
+            echo "Some tests failed! Failing workflow."
+            exit 1
+          fi
