Moved failed condition to test step

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -39,20 +39,25 @@ jobs:
           COVERAGE=$(grep -oP '<span class="pc_cov">\K[0-9]+' backend/htmlcov/index.html)
           echo "coverage=$COVERAGE" >> "$GITHUB_ENV"
 
-          #      - name: Get PR Number
-          #        uses: jwalton/gh-find-current-pr@master
-          #        id: findPr
-          #        with:
-          #          state: open
-          #
-          #      - name: Comment summary
-          #        uses: peter-evans/create-or-update-comment@v4
-          #        with:
-          #          issue-number: ${{ steps.findPr.outputs.pr }}
-          #          body: |
-          #            Passed: ${{ env.passed }}
-          #            Failed: ${{ env.failed }}
-          #            Coverage: ${{ env.coverage }}%
+          if [[ "${{ env.failed }}" -ne 0 ]]; then
+            echo "Some tests failed! Failing workflow."
+            exit 1
+          fi
+           
+#      - name: Get PR Number
+#        uses: jwalton/gh-find-current-pr@master
+#        id: findPr
+#        with:
+#          state: open
+#
+#      - name: Comment summary
+#        uses: peter-evans/create-or-update-comment@v4
+#        with:
+#          issue-number: ${{ steps.findPr.outputs.pr }}
+#          body: |
+#            Passed: ${{ env.passed }}
+#            Failed: ${{ env.failed }}
+#            Coverage: ${{ env.coverage }}%
 
       - name: Upload Coverage Report as Artifact
         uses: actions/upload-artifact@v4
@@ -78,7 +83,3 @@ jobs:
 
       - name: Fail if tests failed
         run: |
-          if [[ "${{ env.failed }}" -ne 0 ]]; then
-            echo "Some tests failed! Failing workflow."
-            exit 1
-          fi
